In [ ]:
from google.colab import drive
import pandas as pd
from tqdm import tqdm

drive.mount('/content/drive')
path = '/content/drive/MyDrive/6000_IMDB_Dataset.csv'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
from transformers import BertTokenizer, BertModel
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split
from transformers import AdamW
import torch
import torch.nn as nn
import torch.nn.functional as F
import math

review_df = pd.read_csv(path)
feature = review_df['review'].tolist()
label = review_df['sentiment'].tolist()

for i in range(len(label)):
    if label[i] == 'positive':
        label[i] = 1
    else :
        label[i] = 0

train_texts,test_texts, train_labels,test_labels = train_test_split(feature, label, train_size=0.7, shuffle=True)

# 토큰화
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
train_encodings = tokenizer(train_texts, truncation=True, padding=True, return_tensors='pt')
test_encodings = tokenizer(test_texts, truncation=True, padding=True, return_tensors='pt')

/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [ ]:
## 기존 bertforseqclassification
from transformers import BertPreTrainedModel
from transformers import PreTrainedModel
from transformers import BertConfig
from typing import List, Optional, Tuple, Union
from transformers.utils import (
    add_code_sample_docstrings,
    add_start_docstrings,
    add_start_docstrings_to_model_forward,
    get_torch_version,
    replace_return_docstrings,
    ModelOutput,
    logging
)

from transformers.modeling_outputs import (
    BaseModelOutputWithPastAndCrossAttentions,
    BaseModelOutputWithPoolingAndCrossAttentions,
    CausalLMOutputWithCrossAttentions,
    MaskedLMOutput,
    MultipleChoiceModelOutput,
    NextSentencePredictorOutput,
    QuestionAnsweringModelOutput,
    SequenceClassifierOutput,
    TokenClassifierOutput,
)

from torch.nn import BCEWithLogitsLoss, CrossEntropyLoss, MSELoss

class BertForSequenceClassification(BertPreTrainedModel):
    def __init__(self, config):
        super().__init__(config)
        self.num_labels = config.num_labels
        self.config = config

        self.bert = BertModel(config)
        classifier_dropout = (
            config.classifier_dropout if config.classifier_dropout is not None else config.hidden_dropout_prob
        )
        self.dropout = nn.Dropout(classifier_dropout)
        self.classifier = nn.Linear(config.hidden_size, config.num_labels)

        # Initialize weights and apply final processing
        self.post_init()

    """
    @add_start_docstrings_to_model_forward(BERT_INPUTS_DOCSTRING.format("batch_size, sequence_length"))
    @add_code_sample_docstrings(
        checkpoint=_CHECKPOINT_FOR_SEQUENCE_CLASSIFICATION,
        output_type=SequenceClassifierOutput,
        config_class=_CONFIG_FOR_DOC,
        expected_output=_SEQ_CLASS_EXPECTED_OUTPUT,
        expected_loss=_SEQ_CLASS_EXPECTED_LOSS,
    )
    """
    def forward(
        self,
        input_ids: Optional[torch.Tensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        token_type_ids: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.Tensor] = None,
        head_mask: Optional[torch.Tensor] = None,
        inputs_embeds: Optional[torch.Tensor] = None,
        labels: Optional[torch.Tensor] = None,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        return_dict: Optional[bool] = None,
    ) -> Union[Tuple[torch.Tensor], SequenceClassifierOutput]:
        r"""
        labels (`torch.LongTensor` of shape `(batch_size,)`, *optional*):
            Labels for computing the sequence classification/regression loss. Indices should be in `[0, ...,
            config.num_labels - 1]`. If `config.num_labels == 1` a regression loss is computed (Mean-Square loss), If
            `config.num_labels > 1` a classification loss is computed (Cross-Entropy).
        """
        return_dict = return_dict if return_dict is not None else self.config.use_return_dict

        outputs = self.bert(
            input_ids,
            attention_mask=attention_mask,
            token_type_ids=token_type_ids,
            position_ids=position_ids,
            head_mask=head_mask,
            inputs_embeds=inputs_embeds,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            return_dict=return_dict,
        )

        pooled_output = outputs[1]

        pooled_output = self.dropout(pooled_output)
        logits = self.classifier(pooled_output)

        loss = None
        if labels is not None:
            if self.config.problem_type is None:
                if self.num_labels == 1:
                    self.config.problem_type = "regression"
                elif self.num_labels > 1 and (labels.dtype == torch.long or labels.dtype == torch.int):
                    self.config.problem_type = "single_label_classification"
                else:
                    self.config.problem_type = "multi_label_classification"

            if self.config.problem_type == "regression":
                loss_fct = MSELoss()
                if self.num_labels == 1:
                    loss = loss_fct(logits.squeeze(), labels.squeeze())
                else:
                    loss = loss_fct(logits, labels)
            elif self.config.problem_type == "single_label_classification":
                loss_fct = CrossEntropyLoss()
                loss = loss_fct(logits.view(-1, self.num_labels), labels.view(-1))
            elif self.config.problem_type == "multi_label_classification":
                loss_fct = BCEWithLogitsLoss()
                loss = loss_fct(logits, labels)
        if not return_dict:
            output = (logits,) + outputs[2:]
            return ((loss,) + output) if loss is not None else output

        return SequenceClassifierOutput(
            loss=loss,
            logits=logits,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
        )

# 사전 훈련된 BERT 모델 이름 설정
config = BertConfig.from_pretrained('bert-base-uncased')
print(config)
config = BertConfig(
    num_labels=2,
    hidden_dropout_prob=0.2,
    classifier_dropout=0.1,
)
"""
default
"attention_probs_dropout_prob": 0.1,
"classifier_dropout": null,
"gradient_checkpointing": false,
"hidden_act": "gelu",
"hidden_dropout_prob": 0.1,
"hidden_size": 768,
"initializer_range": 0.02,
"intermediate_size": 3072,
"layer_norm_eps": 1e-12,
"max_position_embeddings": 512,
"model_type": "bert",
"num_attention_heads": 12,
"num_hidden_layers": 12,
"pad_token_id": 0,
"position_embedding_type": "absolute",
"transformers_version": "4.40.2",
"type_vocab_size": 2,
"use_cache": true,
"vocab_size": 30522
"""


# 새로운 설정으로 모델 초기화
model = BertForSequenceClassification.from_pretrained('bert-base-uncased', config=config)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.40.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}



In [ ]:
# 훈련 설정
optimizer = AdamW(model.parameters(), lr=5e-5)

# 데이터셋 생성
train_dataset = TensorDataset(train_encodings['input_ids'], train_encodings['attention_mask'], torch.tensor(train_labels))
test_dataset = TensorDataset(test_encodings['input_ids'], test_encodings['attention_mask'], torch.tensor(test_labels))

# 데이터로더 생성
train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=8, shuffle=True)

epoch_num = 1
model.train()
for epoch in range(epoch_num):
    for batch in tqdm(train_loader):
        optimizer.zero_grad()
        input_ids, attention_mask, labels = batch
        outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
        print(outputs.logits)
        print(labels)
        print(torch.argmax(outputs.logits, dim=1))
        loss = outputs.loss
        loss.backward()
        optimizer.step()

# 평가
model.eval()
correct = 0
total = 0
with torch.no_grad():
    for batch in test_loader:
        input_ids, attention_mask, labels = batch
        outputs = model(input_ids, attention_mask=attention_mask)
        logits = outputs.logits
        predicted_labels = torch.argmax(logits, dim=1)
        total += labels.size(0)
        correct += (predicted_labels == labels).sum().item()


accuracy = correct / total
print(f'테스트 정확도: {accuracy}')


/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:521: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
  0%|          | 0/525 [00:00<?, ?it/s]

tensor([[ 0.1026, -0.0021],
        [-0.0208, -0.0363],
        [-0.0441,  0.0315],
        [ 0.1712, -0.2988],
        [ 0.1308, -0.1072],
        [ 0.0385, -0.0526],
        [ 0.2350, -0.0773],
        [ 0.0065, -0.0692]], grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 1, 1, 1, 1, 0])
tensor([0, 0, 1, 0, 0, 0, 0, 0])


  0%|          | 1/525 [00:03<29:49,  3.41s/it]

tensor([[-0.1757,  0.0033],
        [-0.0155,  0.4972],
        [-0.0168,  0.3541],
        [ 0.0242,  0.3053],
        [-0.0098,  0.3098],
        [-0.0557,  0.2992],
        [-0.0482,  0.1509],
        [ 0.0113,  0.2492]], grad_fn=<AddmmBackward0>)
tensor([0, 1, 1, 0, 0, 1, 1, 1])
tensor([1, 1, 1, 1, 1, 1, 1, 1])


  0%|          | 2/525 [00:06<30:26,  3.49s/it]

tensor([[-0.0439,  0.7214],
        [-0.2225,  0.2886],
        [-0.0586,  0.6125],
        [-0.1307,  0.2140],
        [-0.2039,  0.5121],
        [-0.1675,  0.6492],
        [-0.2102,  0.7138],
        [-0.0723,  0.6923]], grad_fn=<AddmmBackward0>)
tensor([1, 0, 0, 1, 1, 1, 1, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1])


  1%|          | 3/525 [00:10<29:14,  3.36s/it]

tensor([[-0.0655,  0.7259],
        [ 0.2303,  0.9568],
        [-0.1049,  0.5347],
        [-0.0816,  0.5183],
        [-0.2059,  0.7268],
        [-0.0161,  1.1027],
        [-0.0918,  0.9386],
        [-0.0561,  0.9047]], grad_fn=<AddmmBackward0>)
tensor([0, 1, 0, 1, 1, 1, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1])


  1%|          | 4/525 [00:13<28:06,  3.24s/it]

tensor([[-0.1459,  0.7378],
        [-0.2410,  0.7331],
        [-0.2005,  0.9032],
        [ 0.0572,  0.9492],
        [-0.0029,  0.6285],
        [-0.0564,  0.9685],
        [-0.0807,  0.5612],
        [-0.1175,  0.4533]], grad_fn=<AddmmBackward0>)
tensor([1, 0, 0, 1, 1, 0, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1])


  1%|          | 5/525 [00:16<28:07,  3.24s/it]

tensor([[ 0.0139,  0.2437],
        [ 0.0181,  0.4821],
        [-0.1150,  0.4572],
        [-0.0137,  0.0963],
        [ 0.0278,  0.0438],
        [ 0.0065,  0.5619],
        [ 0.1678,  0.6155],
        [-0.1451,  0.3987]], grad_fn=<AddmmBackward0>)
tensor([1, 0, 0, 1, 0, 1, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1])


  1%|          | 6/525 [00:19<27:54,  3.23s/it]

tensor([[-0.2139, -0.1281],
        [-0.1715, -0.2307],
        [-0.1354, -0.0320],
        [ 0.0218, -0.1352],
        [ 0.0842, -0.1732],
        [-0.1879, -0.4447],
        [-0.0542,  0.0108],
        [-0.4107, -0.0613]], grad_fn=<AddmmBackward0>)
tensor([0, 1, 1, 1, 1, 0, 0, 0])
tensor([1, 0, 1, 0, 0, 0, 1, 1])


  1%|▏         | 7/525 [00:22<26:31,  3.07s/it]

tensor([[ 0.1443, -0.0682],
        [-0.1907, -0.4914],
        [ 0.0918, -0.2504],
        [ 0.1468, -0.0021],
        [-0.1127, -0.1630],
        [-0.1561, -0.2223],
        [-0.2191, -0.2050],
        [-0.0965, -0.1725]], grad_fn=<AddmmBackward0>)
tensor([1, 0, 0, 0, 1, 1, 1, 0])
tensor([0, 0, 0, 0, 0, 0, 1, 0])


  2%|▏         | 8/525 [00:25<26:02,  3.02s/it]

tensor([[-0.0239, -0.2590],
        [-0.1568, -0.1298],
        [-0.0051, -0.7410],
        [ 0.0579, -0.3017],
        [-0.0477, -0.0201],
        [-0.0452, -0.4342],
        [-0.2638, -0.1436],
        [ 0.0817, -0.3568]], grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 0, 1, 0, 0, 0])
tensor([0, 1, 0, 0, 1, 0, 1, 0])


  2%|▏         | 9/525 [00:28<26:00,  3.02s/it]

tensor([[-0.1930, -0.3231],
        [ 0.0743, -0.1689],
        [-0.1009, -0.3151],
        [-0.1263, -0.4502],
        [ 0.2116, -0.3011],
        [-0.0450, -0.3428],
        [ 0.0929, -0.2383],
        [-0.3061, -0.6285]], grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 0, 0, 0, 1, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0])


  2%|▏         | 10/525 [00:31<26:22,  3.07s/it]

tensor([[-0.3300, -0.6464],
        [-0.1232, -0.6951],
        [-0.1745, -0.3450],
        [ 0.0074, -0.3840],
        [-0.0919, -0.0763],
        [-0.0427, -0.3686],
        [-0.0657, -0.3790],
        [ 0.0113, -0.3013]], grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0, 0, 1, 1, 1])
tensor([0, 0, 0, 0, 1, 0, 0, 0])


  2%|▏         | 11/525 [00:34<26:49,  3.13s/it]

tensor([[-0.0115, -0.2972],
        [ 0.0640, -0.2762],
        [ 0.2119, -0.0233],
        [ 0.1227, -0.2792],
        [-0.1894, -0.6822],
        [-0.2029, -0.3668],
        [-0.2178, -0.5903],
        [-0.1391, -0.3006]], grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 1, 1, 1, 1, 1])
tensor([0, 0, 0, 0, 0, 0, 0, 0])


  2%|▏         | 12/525 [00:38<27:11,  3.18s/it]

tensor([[ 0.0419, -0.3981],
        [-0.0006, -0.5134],
        [-0.1062, -0.3321],
        [-0.0401, -0.3518],
        [ 0.1395, -0.4045],
        [-0.0737, -0.2969],
        [ 0.1981, -0.2799],
        [-0.0314, -0.2869]], grad_fn=<AddmmBackward0>)
tensor([1, 1, 1, 0, 0, 0, 1, 1])
tensor([0, 0, 0, 0, 0, 0, 0, 0])


  2%|▏         | 13/525 [00:41<26:25,  3.10s/it]

tensor([[-0.1025, -0.3087],
        [-0.0053, -0.2799],
        [ 0.2099, -0.6604],
        [-0.0853, -0.3426],
        [ 0.0322, -0.5001],
        [-0.0447, -0.5905],
        [ 0.0167, -0.4938],
        [ 0.0515, -0.0652]], grad_fn=<AddmmBackward0>)
tensor([1, 1, 1, 1, 0, 1, 0, 1])
tensor([0, 0, 0, 0, 0, 0, 0, 0])


  3%|▎         | 14/525 [00:44<26:29,  3.11s/it]

tensor([[ 0.1151, -0.4022],
        [ 0.1452, -0.2315],
        [ 0.0496, -0.3559],
        [ 0.0232, -0.4198],
        [ 0.0697, -0.1999],
        [-0.1766,  0.0665],
        [ 0.0214, -0.4078],
        [-0.0890, -0.0779]], grad_fn=<AddmmBackward0>)
tensor([0, 1, 1, 0, 0, 0, 1, 0])
tensor([0, 0, 0, 0, 0, 1, 0, 1])


  3%|▎         | 15/525 [00:47<26:51,  3.16s/it]

tensor([[-0.1579, -0.0831],
        [-0.1421, -0.2024],
        [-0.1737, -0.2681],
        [ 0.1380, -0.0772],
        [-0.4691, -0.3118],
        [-0.1092, -0.4954],
        [ 0.0879, -0.4736],
        [ 0.0625,  0.0406]], grad_fn=<AddmmBackward0>)
tensor([1, 0, 0, 0, 0, 1, 1, 0])
tensor([1, 0, 0, 0, 1, 0, 0, 0])


  3%|▎         | 16/525 [00:50<27:15,  3.21s/it]

tensor([[ 0.0813, -0.1805],
        [-0.3815, -0.2522],
        [-0.2825, -0.2824],
        [ 0.0978, -0.0703],
        [-0.2481, -0.3394],
        [-0.1469, -0.4457],
        [-0.1532, -0.2198],
        [-0.2948,  0.0397]], grad_fn=<AddmmBackward0>)
tensor([0, 1, 1, 1, 0, 1, 0, 0])
tensor([0, 1, 1, 0, 0, 0, 0, 1])


  3%|▎         | 17/525 [00:53<27:12,  3.21s/it]

tensor([[-0.2379, -0.2223],
        [-0.0915, -0.3933],
        [-0.2768, -0.1818],
        [-0.0463, -0.0646],
        [-0.0646, -0.1727],
        [-0.0565, -0.1495],
        [-0.2249, -0.2566],
        [-0.1692, -0.2083]], grad_fn=<AddmmBackward0>)
tensor([0, 1, 0, 1, 0, 0, 0, 1])
tensor([1, 0, 1, 0, 0, 0, 0, 0])


  3%|▎         | 18/525 [00:56<26:41,  3.16s/it]

tensor([[-0.0692,  0.2621],
        [ 0.0685, -0.2485],
        [-0.0085, -0.3026],
        [-0.3799, -0.0698],
        [-0.0616, -0.0074],
        [-0.2351, -0.1583],
        [-0.0271,  0.1271],
        [-0.2068,  0.1091]], grad_fn=<AddmmBackward0>)
tensor([1, 0, 1, 1, 0, 1, 0, 1])
tensor([1, 0, 0, 1, 1, 1, 1, 1])


  4%|▎         | 19/525 [01:00<26:24,  3.13s/it]

tensor([[-8.7398e-02, -1.2414e-01],
        [-1.1736e-01,  2.1862e-01],
        [-1.1034e-01,  1.1441e-03],
        [ 9.0555e-06, -2.0042e-01],
        [-4.1709e-01, -2.2962e-01],
        [-1.3461e-01, -2.3895e-02],
        [-3.0085e-01, -9.7719e-02],
        [-4.6389e-01, -2.6663e-01]], grad_fn=<AddmmBackward0>)
tensor([0, 1, 1, 1, 0, 0, 1, 1])
tensor([0, 1, 1, 0, 1, 1, 1, 1])


  4%|▍         | 20/525 [01:03<26:35,  3.16s/it]

tensor([[ 0.0024, -0.1996],
        [ 0.0230, -0.1440],
        [-0.2088, -0.2075],
        [-0.2448,  0.0097],
        [-0.2344, -0.2221],
        [-0.1854,  0.0911],
        [-0.2900, -0.3012],
        [-0.1005,  0.3007]], grad_fn=<AddmmBackward0>)
tensor([1, 0, 0, 1, 0, 1, 0, 1])
tensor([0, 0, 1, 1, 1, 1, 0, 1])


  4%|▍         | 21/525 [01:06<26:33,  3.16s/it]

tensor([[-0.0905,  0.1394],
        [-0.3247,  0.1456],
        [-0.3581, -0.0920],
        [-0.1321, -0.1669],
        [ 0.2071, -0.0502],
        [-0.1291, -0.5646],
        [ 0.0237,  0.1763],
        [-0.1041, -0.2020]], grad_fn=<AddmmBackward0>)
tensor([0, 1, 0, 1, 1, 1, 1, 0])
tensor([1, 1, 1, 0, 0, 0, 1, 0])


  4%|▍         | 22/525 [01:09<27:07,  3.24s/it]